test

diff --git a/.github/workflows/build-and-publish.yml b/.github/workflows/build-and-publish.yml
--- a/.github/workflows/build-and-publish.yml
+++ b/.github/workflows/build-and-publish.yml
@@ -58,21 +58,27 @@ jobs:
       - name: Publish to NuGet
         run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
 
-      - name: Get version from csproj
-        id: get_version_and_changelog
-        run: |
-          VERSION=$(sed -n 's/.*<Version>\(.*\)<\/Version>.*/\1/p' ConsoleTable.Text/ConsoleTable.Text.csproj)
-          if [ -z "$VERSION" ]; then
-            echo "Error: Could not extract version from ConsoleTable.csproj"
-            exit 1
-          fi
-          echo "Found version: $VERSION""
-          echo "version=$VERSION" >> $GITHUB_OUTPUT
+      - name: Parse csproj for Version
+        id: parse_version
+        uses: cschleiden/parse-xml@v1
+        with:
+          file: ConsoleTable.Text/ConsoleTable.Text.csproj
+          xpath: //Version
+
+      # - name: Get version from csproj
+      #   id: get_version_and_changelog
+      #   run: |
+      #     VERSION=$(sed -n 's/.*<Version>\(.*\)<\/Version>.*/\1/p' ConsoleTable.Text/ConsoleTable.Text.csproj)
+      #     if [ -z "$VERSION" ]; then
+      #       echo "Error: Could not extract version from ConsoleTable.csproj"
+      #       exit 1
+      #     fi
+      #     echo "version=$VERSION" >> $GITHUB_OUTPUT
 
       - name: Get release notes from ChangeLog folder with version
         id: get_releasenotes
         run: |
-          VERSION="${{ steps.get_version.outputs.version }}"
+          VERSION="${{ steps.parse_version.outputs.value }}"
           CHANGELOG_FILE="ChangeLogs/${VERSION}-changelog.md"
           if [ ! -f "$CHANGELOG_FILE" ]; then
             echo "Error: Changelog file $CHANGELOG_FILE not found"
@@ -88,8 +94,8 @@ jobs:
       - name: Create GitHub Release
         uses: softprops/action-gh-release@v2
         with:
-          tag_name: v${{ steps.get_version.outputs.version }}
-          name: Release v${{ steps.get_version.outputs.version }}
+          tag_name: v${{ steps.parse_version.outputs.value }}
+          name: Release v${{ steps.parse_version.outputs.value }}
           body: v${{ steps.get_releasenotes.outputs.releasenotes }}
         # env:
         #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
